# Generated by Django 5.2.17 on 2026-09-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('LEAVE_APPROVED', 'Leave Approved'), ('LEAVE_REJECTED', 'Leave Rejected'), ('TIMESHEET_APPROVED', 'Timesheet Approved'), ('TIMESHEET_REJECTED', 'Timesheet Rejected'), ('PAYROLL_PROCESSED', 'Payroll Processed'), ('PERFORMANCE_PENDING', 'Performance Review Pending'), ('WORK_ALLOCATED', 'New Work Allocated'), ('ANNOUNCEMENT', 'Announcement')], default='ANNOUNCEMENT', max_length=30)),
                ('is_read', models.BooleanField(default=False)),
                ('target_url', models.CharField(blank=True, max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
