# Generated by Django 5.2.17 on 2026-09-08 14:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerformancePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Q1 2026 Review, Annual Review 2026', max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('UPCOMING', 'Upcoming'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('target_date', models.DateField()),
                ('progress_percentage', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.DecimalField(decimal_places=1, default=1.0, max_digits=4)),
                ('status', models.CharField(choices=[('NOT_STARTED', 'Not Started'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed')], default='NOT_STARTED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='performance.performanceperiod')),
            ],
            options={
                'ordering': ['target_date'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('self_rating', models.DecimalField(blank=True, decimal_places=1, help_text='1.0 to 5.0', max_digits=3, null=True)),
                ('manager_rating', models.DecimalField(blank=True, decimal_places=1, help_text='1.0 to 5.0', max_digits=3, null=True)),
                ('final_score', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True)),
                ('rating_grade', models.CharField(choices=[('EXCEEDS_EXPECTATIONS', 'Exceeds Expectations'), ('MEETS_EXPECTATIONS', 'Meets Expectations'), ('NEEDS_IMPROVEMENT', 'Needs Improvement'), ('UNSATISFACTORY', 'Unsatisfactory')], default='MEETS_EXPECTATIONS', max_length=30)),
                ('employee_comments', models.TextField(blank=True, null=True)),
                ('manager_comments', models.TextField(blank=True, null=True)),
                ('is_submitted_by_employee', models.BooleanField(default=False)),
                ('is_completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='employees.employee')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='performance.performanceperiod')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-period__start_date'],
                'unique_together': {('employee', 'period')},
            },
        ),
    ]
